version: '3.7'

services:
  web:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules # <---- this enables a much faster start/reload
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading
